export default [
  { title: 'Горный пейзаж', name: 'elena-remizova-paint-mountains-landscape' },
  { title: 'Лицо мамы', name: 'elena-remizova-paint-portrait-moms-face' },
  { title: 'Портрет Джеро', name: 'elena-remizova-paint-portrait-jero' },
  { title: 'Женский образ', name: 'elena-remizova-paint-portrait-image-woman' },
  { title: 'Скала, Гуатапе', name: 'elena-remizova-paint-rock-guatape' },
  { title: 'Портрет девушки', name: 'elena-remizova-paint-portrait-girl' },
  { title: 'Дорога в горах', name: 'elena-remizova-paint-road-in-the-mountains' },
  { title: 'Деревенское озеро', name: 'elena-remizova-paint-village-lake' },
  { title: 'Город. Рассвет', name: 'elena-remizova-paint-town-dawn' },
  { title: 'Берёзовая роща', name: 'elena-remizova-paint-birch-grove' },
  { title: 'Осенний лес', name: 'elena-remizova-paint-autumn-forest' },
  { title: 'Люпины', name: 'elena-remizova-paint-lupines' },
  { title: 'Портрет друга', name: 'elena-remizova-paint-portrait-friend' },
  {
    title: 'Любимый друг',
    name: 'elena-remizova-paint-portrait-beloved-friend',
  },
  { title: 'Мужской образ', name: 'elena-remizova-paint-portrait-image-man' },
  { title: 'Розовый закат', name: 'elena-remizova-paint-pink-sunset' },
  {
    title: 'Обнажённая женщина',
    name: 'elena-remizova-paint-portrait-nuded-woman',
  },
  { title: 'Осенний пейзаж', name: 'elena-remizova-paint-autumn-landscape' },
];
